# Replace the example Token with YOUR token otherwise the Bot won't work!  [String]
Token: ""

# Enter here the Opus File, On Windows its libopus-0.x86.dll or libopus-0.x64.dll on Linux it is usally libopus.so.0 [String]
OpusFile: "libopus-0.x86.dll"

# Set the Prefix of the Bot [String]
Prefix: "!"

# Please enter here the Role a User need for the Admin Commands [String]
AdminRole: "DJ"

# Base Volume; Here you can change the default Base Volume! [Float]
Volume: 0.1

SettingsFolder: "settings"

TokenFile: "my.token"

InviteLink: "https://discordapp.com/oauth2/authorize?client_id=462304443954888724&scope=bot"
